// <auto-generated />
using System;
using Company.Data.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Company.Data.Migrations
{
    [DbContext(typeof(CompanyContext))]
    [Migration("20260104110618_OrderMigration")]
    partial class OrderMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Company.Data.Data.CMS.News", b =>
                {
                    b.Property<int>("IdNews")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdNews"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LinkTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdNews");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            IdNews = 1,
                            Content = "<p>Zapraszamy na wielką wyprzedaż zimową! Rabaty do 50% na wybrane produkty. Promocja trwa do końca miesiąca.</p><p>Nie przegap okazji!</p>",
                            DisplayOrder = 1,
                            LinkTitle = "Wielka wyprzedaż",
                            Title = "Wielka wyprzedaż zimowa!"
                        },
                        new
                        {
                            IdNews = 2,
                            Content = "<p>Z przyjemnością informujemy, że nowa kolekcja produktów jest już dostępna w naszym sklepie.</p><p>Sprawdź najnowsze trendy i wybierz coś dla siebie!</p>",
                            DisplayOrder = 2,
                            LinkTitle = "Nowa kolekcja",
                            Title = "Nowa kolekcja już dostępna"
                        },
                        new
                        {
                            IdNews = 3,
                            Content = "<p>Miło nam poinformować, że od teraz oferujemy darmową dostawę przy zamówieniach powyżej 100 zł.</p><p>Zamów już dziś i skorzystaj z promocji!</p>",
                            DisplayOrder = 3,
                            LinkTitle = "Darmowa dostawa",
                            Title = "Darmowa dostawa od 100 zł"
                        },
                        new
                        {
                            IdNews = 4,
                            Content = "<p>W okresie świątecznym pracujemy w zmienionych godzinach:</p><ul><li>24.12 - 8:00 - 12:00</li><li>25-26.12 - zamknięte</li><li>31.12 - 8:00 - 14:00</li></ul>",
                            DisplayOrder = 4,
                            LinkTitle = "Godziny świąteczne",
                            Title = "Zmiana godzin pracy"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.CMS.Page", b =>
                {
                    b.Property<int>("IdPage")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPage"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(MAX)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<string>("LinkTitle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdPage");

                    b.ToTable("Page");

                    b.HasData(
                        new
                        {
                            IdPage = 1,
                            Content = "<p>Jesteśmy firmą z wieloletnim doświadczeniem na rynku. Specjalizujemy się w dostarczaniu najwyższej jakości produktów i usług dla naszych klientów.</p><p>Nasza misja to zapewnienie satysfakcji każdego klienta poprzez profesjonalną obsługę i konkurencyjne ceny.</p>",
                            DisplayOrder = 1,
                            LinkTitle = "O nas",
                            Title = "O naszej firmie"
                        },
                        new
                        {
                            IdPage = 2,
                            Content = "<p><strong>Adres:</strong> ul. Przykładowa 123, 00-001 Warszawa</p><p><strong>Telefon:</strong> +48 123 456 789</p><p><strong>Email:</strong> kontakt@firma.pl</p><p>Zapraszamy od poniedziałku do piątku w godzinach 8:00 - 16:00</p>",
                            DisplayOrder = 2,
                            LinkTitle = "Kontakt",
                            Title = "Skontaktuj się z nami"
                        },
                        new
                        {
                            IdPage = 3,
                            Content = "<h3>§1 Postanowienia ogólne</h3><p>Niniejszy regulamin określa zasady korzystania ze sklepu internetowego.</p><h3>§2 Składanie zamówień</h3><p>Zamówienia można składać 24 godziny na dobę, 7 dni w tygodniu.</p><h3>§3 Płatności</h3><p>Akceptujemy płatności kartą, przelewem oraz za pobraniem.</p>",
                            DisplayOrder = 3,
                            LinkTitle = "Regulamin",
                            Title = "Regulamin sklepu"
                        },
                        new
                        {
                            IdPage = 4,
                            Content = "<p>Szanujemy Twoją prywatność. Wszystkie dane osobowe są przetwarzane zgodnie z RODO.</p><p>Twoje dane wykorzystujemy wyłącznie w celu realizacji zamówień i nie udostępniamy ich podmiotom trzecim.</p>",
                            DisplayOrder = 4,
                            LinkTitle = "Polityka prywatności",
                            Title = "Polityka prywatności"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.CartItem", b =>
                {
                    b.Property<int>("IdCartItem")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCartItem"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<string>("IdSessionOfCart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdCartItem");

                    b.HasIndex("IdProduct");

                    b.ToTable("CartItem");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Order", b =>
                {
                    b.Property<int>("IdOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrder"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("nvarchar(160)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("nvarchar(24)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Voivodeship")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("nvarchar(70)");

                    b.Property<string>("ZipCode")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("IdOrder");

                    b.ToTable("Order");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.OrderPosition", b =>
                {
                    b.Property<int>("IdOrderPosition")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdOrderPosition"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdOrder")
                        .HasColumnType("int");

                    b.Property<int>("IdProduct")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("IdOrderPosition");

                    b.HasIndex("IdOrder");

                    b.HasIndex("IdProduct");

                    b.ToTable("OrderPosition");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Product", b =>
                {
                    b.Property<int>("IdProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FotoURL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IdTypeOfProduct")
                        .HasColumnType("int");

                    b.Property<bool>("IsDiscount")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("money");

                    b.HasKey("IdProduct");

                    b.HasIndex("IdTypeOfProduct");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            IdProduct = 1,
                            Code = "ELEC-001",
                            Description = "Nowoczesny smartfon z ekranem AMOLED 6.5\", 128GB pamięci, aparat 48MP",
                            FotoURL = "https://via.placeholder.com/300x300?text=Smartfon",
                            IdTypeOfProduct = 1,
                            IsDiscount = true,
                            Name = "Smartfon Galaxy X",
                            Price = 2499.99m
                        },
                        new
                        {
                            IdProduct = 2,
                            Code = "ELEC-002",
                            Description = "Wydajny laptop z procesorem i7, 16GB RAM, dysk SSD 512GB",
                            FotoURL = "https://via.placeholder.com/300x300?text=Laptop",
                            IdTypeOfProduct = 1,
                            IsDiscount = false,
                            Name = "Laptop ProBook 15",
                            Price = 3999.00m
                        },
                        new
                        {
                            IdProduct = 3,
                            Code = "ELEC-003",
                            Description = "Bezprzewodowe słuchawki z aktywną redukcją szumów, 30h pracy",
                            FotoURL = "https://via.placeholder.com/300x300?text=Sluchawki",
                            IdTypeOfProduct = 1,
                            IsDiscount = true,
                            Name = "Słuchawki Bluetooth",
                            Price = 299.99m
                        },
                        new
                        {
                            IdProduct = 4,
                            Code = "CLOTH-001",
                            Description = "Wygodna koszulka z bawełny organicznej, dostępna w wielu kolorach",
                            FotoURL = "https://via.placeholder.com/300x300?text=Koszulka",
                            IdTypeOfProduct = 2,
                            IsDiscount = false,
                            Name = "Koszulka Basic",
                            Price = 49.99m
                        },
                        new
                        {
                            IdProduct = 5,
                            Code = "CLOTH-002",
                            Description = "Klasyczne jeansy o dopasowanym kroju, wysoka jakość denimu",
                            FotoURL = "https://via.placeholder.com/300x300?text=Jeansy",
                            IdTypeOfProduct = 2,
                            IsDiscount = true,
                            Name = "Jeansy Slim Fit",
                            Price = 149.99m
                        },
                        new
                        {
                            IdProduct = 6,
                            Code = "CLOTH-003",
                            Description = "Ciepła kurtka zimowa z kapturem, wodoodporna, rozmiary S-XXL",
                            FotoURL = "https://via.placeholder.com/300x300?text=Kurtka",
                            IdTypeOfProduct = 2,
                            IsDiscount = false,
                            Name = "Kurtka zimowa",
                            Price = 399.00m
                        },
                        new
                        {
                            IdProduct = 7,
                            Code = "HOME-001",
                            Description = "Elegancka lampa stołowa LED z regulacją jasności",
                            FotoURL = "https://via.placeholder.com/300x300?text=Lampa",
                            IdTypeOfProduct = 3,
                            IsDiscount = false,
                            Name = "Lampa stołowa LED",
                            Price = 129.00m
                        },
                        new
                        {
                            IdProduct = 8,
                            Code = "HOME-002",
                            Description = "Stylowa doniczka ceramiczna, idealna na kwiaty doniczkowe",
                            FotoURL = "https://via.placeholder.com/300x300?text=Doniczka",
                            IdTypeOfProduct = 3,
                            IsDiscount = true,
                            Name = "Doniczka ceramiczna",
                            Price = 39.99m
                        },
                        new
                        {
                            IdProduct = 9,
                            Code = "SPORT-001",
                            Description = "Zestaw hantli 2x5kg z powłoką neoprenową",
                            FotoURL = "https://via.placeholder.com/300x300?text=Hantle",
                            IdTypeOfProduct = 4,
                            IsDiscount = false,
                            Name = "Hantle 2x5kg",
                            Price = 89.99m
                        },
                        new
                        {
                            IdProduct = 10,
                            Code = "SPORT-002",
                            Description = "Antypoślizgowa mata do jogi, grubość 6mm, z torbą transportową",
                            FotoURL = "https://via.placeholder.com/300x300?text=Mata",
                            IdTypeOfProduct = 4,
                            IsDiscount = true,
                            Name = "Mata do jogi",
                            Price = 59.99m
                        },
                        new
                        {
                            IdProduct = 11,
                            Code = "BOOK-001",
                            Description = "Kompletny przewodnik po programowaniu w języku C# dla początkujących i zaawansowanych",
                            FotoURL = "https://via.placeholder.com/300x300?text=Ksiazka+CSharp",
                            IdTypeOfProduct = 5,
                            IsDiscount = false,
                            Name = "Programowanie w C#",
                            Price = 79.99m
                        },
                        new
                        {
                            IdProduct = 12,
                            Code = "BOOK-002",
                            Description = "Praktyczny poradnik tworzenia aplikacji webowych w ASP.NET Core MVC",
                            FotoURL = "https://via.placeholder.com/300x300?text=Ksiazka+ASPNET",
                            IdTypeOfProduct = 5,
                            IsDiscount = true,
                            Name = "ASP.NET Core w praktyce",
                            Price = 89.99m
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.TypeOfProduct", b =>
                {
                    b.Property<int>("IdTypeOfProduct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTypeOfProduct"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("IdTypeOfProduct");

                    b.ToTable("TypeOfProduct");

                    b.HasData(
                        new
                        {
                            IdTypeOfProduct = 1,
                            Description = "Smartfony, tablety, laptopy i inne urządzenia elektroniczne",
                            Name = "Elektronika"
                        },
                        new
                        {
                            IdTypeOfProduct = 2,
                            Description = "Koszulki, spodnie, kurtki i inne ubrania",
                            Name = "Odzież"
                        },
                        new
                        {
                            IdTypeOfProduct = 3,
                            Description = "Meble, dekoracje, narzędzia ogrodowe",
                            Name = "Dom i ogród"
                        },
                        new
                        {
                            IdTypeOfProduct = 4,
                            Description = "Sprzęt sportowy, odzież sportowa, akcesoria fitness",
                            Name = "Sport"
                        },
                        new
                        {
                            IdTypeOfProduct = 5,
                            Description = "Literatura, podręczniki, audiobooki",
                            Name = "Książki"
                        });
                });

            modelBuilder.Entity("Company.Data.Data.Shop.CartItem", b =>
                {
                    b.HasOne("Company.Data.Data.Shop.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.OrderPosition", b =>
                {
                    b.HasOne("Company.Data.Data.Shop.Order", "Order")
                        .WithMany("OrderPosition")
                        .HasForeignKey("IdOrder")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Company.Data.Data.Shop.Product", "Product")
                        .WithMany()
                        .HasForeignKey("IdProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Product", b =>
                {
                    b.HasOne("Company.Data.Data.Shop.TypeOfProduct", "TypeOfProduct")
                        .WithMany("Products")
                        .HasForeignKey("IdTypeOfProduct")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TypeOfProduct");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.Order", b =>
                {
                    b.Navigation("OrderPosition");
                });

            modelBuilder.Entity("Company.Data.Data.Shop.TypeOfProduct", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
